apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "application-template.fullname" . }}-scripts
  namespace: {{ .Values.global.namespace }}
data:
  wait-for-readiness.sh: |-
{{ .Files.Get "scripts/wait-for-readiness.sh" | indent 4 }}
  wait-for-kafka.sh: |-
{{ (.Files.Get "scripts/wait-for-kafka.sh") | indent 4 }}